### ISSUE TITLE
For Cuda

### ISSUE THREAD

**Issue by Alexey-T** [saulhudson/saulhudson-color-schemes#3]
Hi
Is it possible to port theme to Cudatext [uvviewsoft.com]?

**Comment by saulhudson** [comment]
I have no experience with Cudatext, in fact I've never heard of it until you mentioned it. However please feel free to copy this colour scheme as you see fit. There is no license and I'm more than happy for others to take it and make it their own. If you make a colour scheme and either want to merge it into this or create or own fork that is absolutely fine.

**Comment by Alexey-T** [comment]
Thanks, in fact Cud has not only color scheme so it is big work, ok
